FROM botbotrobotics/botbrain:base
RUN apt-get update && apt-get install -y \
    liblapacke-dev \
    libglu1-mesa-dev \
    libosmesa6-dev \
    libxi-dev \
    libudev-dev \
    && rm -rf /var/lib/apt/lists/*
